version: '3.8'
services:
  mongodb:
    image: mongo:3.6
    container_name: "db_reporting"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
